# Generated by Django 5.0.4 on 2024-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('garantia', models.CharField(max_length=100)),
                ('accesorios', models.CharField(max_length=100)),
                ('fuente', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('cables', models.CharField(max_length=100)),
                ('caja', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, upload_to='tickets/img1/')),
                ('img2', models.ImageField(blank=True, upload_to='tickets/img2/')),
                ('img3', models.ImageField(blank=True, upload_to='tickets/img3/')),
            ],
        ),
    ]
