# Generated by Django 5.0.4 on 2024-04-16 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('garantia', models.CharField(max_length=100)),
                ('fuente', models.BooleanField(default=False)),
                ('hdd', models.BooleanField(default=False)),
                ('cables', models.BooleanField(default=False)),
                ('caja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, upload_to='tickets/img/')),
                ('img2', models.ImageField(blank=True, upload_to='tickets/img/')),
                ('img3', models.ImageField(blank=True, upload_to='tickets/img/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
