# Generated by Django 5.0.4 on 2024-04-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='defectoDelEquipo',
            field=models.TextField(default=2, max_length=2000),
            preserve_default=False,
        ),
    ]
